apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
spec:
  ports: []
  selector:
    service: web
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: web
