apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    service: web
spec:
  ports:
    - port: 30900
      targetPort: 30900
  selector:
    service: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: web
